In [6]:
import pandas as pd
from sqlalchemy import create_engine

# Below we specify the parameters required to access the db.
host = "localhost"
user = "root"
password = ""
database = "milk_collection_db"

# Create a connection to the db.
connection = f"mysql+pymysql://{user}:{password}@{host}/{database}"

# By use of sql alchemy engine, establish the connection.
engine = create_engine(connection)

# Specify the query you want to execute.
query = """SELECT f.first_name AS farmer_first_name, f.last_name as farmer_last_name, p.amount, p.payment_date, p.status, c.litres * c.price_per_litre as Exact_amout_paid, c.litres, c.price_per_litre, po.first_name AS porter_first_name, po.last_name as porter_last_name FROM farmers f INNER JOIN payments p ON f.farmer_id = p.farmers_id INNER JOIN collections c ON f.farmer_id = c.farmer_id INNER JOIN porters po ON c.porter_id = po.porter_id"""

# Create a dataframe after the query has executed.
df = pd.read_sql_query(query, engine)

# Print out the dataframe.
df

,farmer_first_name,farmer_last_name,amount,payment_date,status,Exact_amout_paid,litres,price_per_litre,porter_first_name,porter_last_name
0,Brian,Ollum,5370.0,2026-10-01,PAID,4708.60,72.44,65.0,Martin,Musembi
1,Brian,Ollum,5370.0,2026-10-01,PAID,3835.00,59.00,65.0,Hadassah,Halima
2,Onesmus,Maitha,6723.0,2026-10-02,PAID,2802.80,43.12,65.0,Martin,Musembi
3,Onesmus,Maitha,6723.0,2026-10-02,PAID,4046.25,62.25,65.0,Hadassah,Halima
4,Maria,Terry,4981.0,2026-10-03,PENDING,3299.40,50.76,65.0,Martin,Musembi
5,Maria,Terry,4981.0,2026-10-03,PENDING,3237.00,49.80,65.0,Raphael,Lisbon
6,Michael,Tsuma,5519.0,2026-10-04,PAID,2537.60,39.04,65.0,Martin,Musembi
7,Michael,Tsuma,5519.0,2026-10-04,PAID,4145.70,63.78,65.0,Raphael,Lisbon
8,Emmanuel,Kukat,6819.0,2026-10-05,PAID,3153.80,48.52,65.0,Malik,Mwangi
9,Emmanuel,Kukat,6819.0,2026-10-05,PAID,5697.90,87.66,65.0,Raphael,Lisbon
10,Lavendar,Simbisa,7041.0,2026-10-06,PENDING,4503.20,69.28,65.0,Malik,Mwangi
11,Lavendar,Simbisa,7041.0,2026-10-06,PENDING,6056.70,93.18,65.0,Raphael,Lisbon
12,Collins,Mutitu,5717.0,2026-10-07,PAID,3938.35,60.59,65.0,Malik,Mwangi
13,Collins,Mutitu,5717.0,2026-10-07,PAID,6259.50,96.30,65.0,Abigael,Apondi
14,Lydia,Aseka,7648.0,2026-10-08,PAID,3153.80,48.52,65.0,Malik,Mwangi
15,Lydia,Aseka,7648.0,2026-10-08,PAID,7330.05,112.77,65.0,Abigael,Apondi
16,Lawrence,Ogutu,6652.0,2026-10-09,PENDING,3452.80,53.12,65.0,Hadassah,Halima
17,Lawrence,Ogutu,6652.0,2026-10-09,PENDING,5269.55,81.07,65.0,Abigael,Apondi
18,Balvin,Brown,8360.0,2026-10-10,PAID,3043.95,46.83,65.0,Hadassah,Halima
19,Balvin,Brown,8360.0,2026-10-10,PAID,3659.50,56.30,65.0,Abigael,Apondi

In [7]:
# Finding the shape of our dataframe.
df.shape

(20, 10)

In [8]:
# Check for some info in regard to the generated df.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   farmer_first_name  20 non-null     str
 1   farmer_last_name   20 non-null     str
 2   amount             20 non-null     float64
 3   payment_date       20 non-null     object
 4   status             20 non-null     str
 5   Exact_amout_paid   20 non-null     float64
 6   litres             20 non-null     float64
 7   price_per_litre    20 non-null     float64
 8   porter_first_name  20 non-null     str
 9   porter_last_name   20 non-null     str
dtypes: float64(4), object(1), str(5)
memory usage: 1.7+ KB

In [9]:
# Summary statistics for numeric columns.
df.describe()

            amount  Exact_amout_paid      litres  price_per_litre
count    20.000000         20.000000   20.000000             20.0
mean   6483.000000       4206.572500   64.716500             65.0
std    1046.377209       1303.475169   20.053464              0.0
min    4981.000000       2537.600000   39.040000             65.0
25%    5519.000000       3216.200000   49.480000             65.0
50%    6687.500000       3886.675000   59.795000             65.0
75%    7041.000000       4848.837500   74.597500             65.0
max    8360.000000       7330.050000  112.770000             65.0

In [11]:
# Below is how we export thr entire df into a csv.
df.to_csv("milk_collection_data.csv", index=False)